[build]
  command = "npm ci && npm run build:next && npm run postbuild"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.18.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"
  # Explicitly tell Netlify to use esbuild as the function bundler
  NETLIFY_USE_ESBUILD = "true"
  # Tell the build to skip unnecessary work
  NEXT_SKIP_TYPECHECK = "true"
  NEXT_EXPORT = "true"

[build.processing]
  skip_processing = false

# Remove prebuild command since we have dependencies in the right place now
[dev]
  framework = "next"

[functions]
  node_bundler = "esbuild"
  # Only mark these as external - they won't be bundled
  external_node_modules = [
    "mammoth", 
    "pdf-parse",
    "@next/font",
    "next",
    "react",
    "react-dom",
    "sharp",
    "@radix-ui/react-dropdown-menu",
    "@radix-ui/react-scroll-area",
    "@radix-ui/react-tabs",
    "@radix-ui/react-tooltip",
    "framer-motion",
    "docx",
    "date-fns",
    "recharts",
    "next-themes",
    "embla-carousel-react",
    "react-day-picker",
    "zod",
    "lucide-react"
  ]
  # Be very selective about which files to include
  included_files = [
    "public/**/*",
    "app/**/*.{js,ts,jsx,tsx}",
    "pages/**/*.{js,ts,jsx,tsx}",
    "lib/**/*.{js,ts,jsx,tsx}",
    "components/**/*.{js,ts,jsx,tsx}",
    "next.config.js",
    "package.json",
    "utils/**/*.{js,ts}"
  ]

# Increase the timeout for API routes to maximum allowed
[functions."api/analyze"]
  included_files = [
    "app/api/analyze/**/*.{js,ts}",
    "app/api/utils/**/*.{js,ts}",
    "lib/netlifyUtils*.{js,ts}", 
    "lib/utils*.{js,ts}"
  ]
  timeout = 26

[functions."api/upload"]
  included_files = [
    "app/api/upload/**/*.{js,ts}",
    "app/api/utils/**/*.{js,ts}",
    "lib/netlifyUtils*.{js,ts}", 
    "lib/utils*.{js,ts}"
  ]
  timeout = 26

# Add deploy context configuration
[context.production]
  environment = { NODE_ENV = "production", NPM_CONFIG_PRODUCTION = "false" }

[context.deploy-preview]
  environment = { NODE_ENV = "production", NPM_CONFIG_PRODUCTION = "false" }

# Configure redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Configure headers for better caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 