[build]
  command = "npm ci && npm install -g postcss tailwindcss && npm run build:next"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.18.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"

[build.processing]
  skip_processing = false

# Add prebuild command to ensure required dependencies are installed
[build.lifecycle]
  onPreBuild = "npm install --silent typescript tailwindcss autoprefixer postcss"

[dev]
  framework = "next"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mammoth", "pdf-parse"]
  included_files = ["node_modules/**", "temp/**"]

# Increase the timeout for API routes to maximum allowed
[functions."api/analyze"]
  included_files = ["node_modules/**", "temp/**"]
  timeout = 26

[functions."api/upload"]
  included_files = ["node_modules/**", "temp/**"]
  timeout = 26

# Add deploy context configuration
[context.production]
  environment = { NODE_ENV = "production", NPM_CONFIG_PRODUCTION = "false" }

[context.deploy-preview]
  environment = { NODE_ENV = "production", NPM_CONFIG_PRODUCTION = "false" }

# Configure redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true 