[build]
  command = "npm ci && npm run build:next"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.18.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"

[build.processing]
  skip_processing = false

# Add prebuild command to ensure required dependencies are installed
[build.lifecycle]
  onPreBuild = "npm install --silent typescript tailwindcss autoprefixer postcss"

[dev]
  framework = "next"

[functions]
  node_bundler = "esbuild"
  # Only mark these as external - they won't be bundled
  external_node_modules = [
    "mammoth", 
    "pdf-parse",
    "@next/font",
    "next",
    "react",
    "react-dom",
    "sharp"
  ]
  # Be more selective about which files to include
  included_files = [
    "public/**",
    "app/**/*.{js,ts,jsx,tsx}",
    "pages/**/*.{js,ts,jsx,tsx}",
    "lib/**/*.{js,ts,jsx,tsx}",
    "components/**/*.{js,ts,jsx,tsx}",
    "next.config.js",
    "package.json",
    "jsconfig.json",
    "tsconfig.json",
    ".env",
    ".env.production",
    ".env.local"
  ]

# Increase the timeout for API routes to maximum allowed
[functions."api/analyze"]
  included_files = [
    "app/api/analyze/**",
    "app/api/utils/**",
    "lib/netlifyUtils*", 
    "lib/utils*"
  ]
  timeout = 26

[functions."api/upload"]
  included_files = [
    "app/api/upload/**",
    "app/api/utils/**",
    "lib/netlifyUtils*", 
    "lib/utils*"
  ]
  timeout = 26

# Add deploy context configuration
[context.production]
  environment = { NODE_ENV = "production", NPM_CONFIG_PRODUCTION = "false" }

[context.deploy-preview]
  environment = { NODE_ENV = "production", NPM_CONFIG_PRODUCTION = "false" }

# Configure redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true 