[build]
  command = "npm ci && npm run build:next && npm run postbuild"
  publish = ".next/standalone"
  ignore = "git diff --quiet HEAD^ HEAD . ':(exclude)netlify.toml'"

[build.environment]
  NODE_VERSION = "18.18.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"
  # Explicitly tell Netlify to use esbuild as the function bundler
  NETLIFY_USE_ESBUILD = "true"
  # Tell the build to skip unnecessary work
  NEXT_SKIP_TYPECHECK = "true"
  NEXT_EXPORT = "true"

[build.processing]
  skip_processing = false

# Remove prebuild command since we have dependencies in the right place now
[dev]
  framework = "next"

[functions]
  # Set the directory of the functions
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # External modules - these won't be bundled
  external_node_modules = [
    "mammoth", 
    "pdf-parse",
    "@next/font",
    "next",
    "react",
    "react-dom",
    "sharp",
    "@radix-ui/react-dropdown-menu",
    "@radix-ui/react-scroll-area",
    "@radix-ui/react-tabs",
    "@radix-ui/react-tooltip",
    "framer-motion",
    "docx",
    "date-fns",
    "recharts",
    "next-themes",
    "embla-carousel-react",
    "react-day-picker",
    "zod",
    "lucide-react",
    "@anthropic-ai/sdk",
    "anthropic"
  ]
  # Only include essential files
  included_files = [
    "netlify/functions/**/*.js",
    "app/api/**/*.js",
    "lib/utils.js",
    "lib/netlifyUtils.js"
  ]

# Specific function configurations
[functions.index]
  # Keep the index function extremely minimal
  external_node_modules = ["*"]
  included_files = ["netlify/functions/index.js", "netlify/functions/implementation.js"]

[functions.config]
  # Keep the config function extremely minimal
  external_node_modules = ["*"]
  included_files = ["netlify/functions/config.js"]

# Configure API functions with minimal included files
[functions."api/analyze"]
  included_files = [
    "app/api/analyze/route.js",
    "app/api/utils/**/*.js",
    "lib/netlifyUtils.js", 
    "lib/utils.js"
  ]
  timeout = 26

[functions."api/upload"]
  included_files = [
    "app/api/upload/route.js",
    "app/api/utils/**/*.js",
    "lib/netlifyUtils.js", 
    "lib/utils.js"
  ]
  timeout = 26

# Add deploy context configuration
[context.production]
  environment = { NODE_ENV = "production", NPM_CONFIG_PRODUCTION = "false" }

[context.deploy-preview]
  environment = { NODE_ENV = "production", NPM_CONFIG_PRODUCTION = "false" }

# Configure redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200
  force = true

# Configure headers for better caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 